# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scenario.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scenario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0escenario.proto\x12\x12waymo.open_dataset\"\x83\x01\n\x08Scenario\x12\x1e\n\x12timestamps_seconds\x18\x01 \x03(\x01\x42\x02\x10\x01\x12)\n\x06tracks\x18\x02 \x03(\x0b\x32\x19.waymo.open_dataset.Track\x12\x13\n\x0bscenario_id\x18\x05 \x01(\t\x12\x17\n\x0fsdc_track_index\x18\x07 \x01(\x05\"y\n\x05Track\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x33\n\x0bobject_type\x18\x02 \x01(\x0e\x32\x1e.waymo.open_dataset.ObjectType\x12/\n\x06states\x18\x03 \x03(\x0b\x32\x1f.waymo.open_dataset.ObjectState\"\xba\x01\n\x0bObjectState\x12\x10\n\x08\x63\x65nter_x\x18\x02 \x01(\x01\x12\x10\n\x08\x63\x65nter_y\x18\x03 \x01(\x01\x12\x10\n\x08\x63\x65nter_z\x18\x04 \x01(\x01\x12\x0e\n\x06length\x18\x05 \x01(\x02\x12\r\n\x05width\x18\x06 \x01(\x02\x12\x0e\n\x06height\x18\x07 \x01(\x02\x12\x0f\n\x07heading\x18\x08 \x01(\x02\x12\x12\n\nvelocity_x\x18\t \x01(\x02\x12\x12\n\nvelocity_y\x18\n \x01(\x02\x12\r\n\x05valid\x18\x0b \x01(\x08*e\n\nObjectType\x12\x0e\n\nTYPE_UNSET\x10\x00\x12\x10\n\x0cTYPE_VEHICLE\x10\x01\x12\x13\n\x0fTYPE_PEDESTRIAN\x10\x02\x12\x10\n\x0cTYPE_CYCLIST\x10\x03\x12\x0e\n\nTYPE_OTHER\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scenario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENARIO'].fields_by_name['timestamps_seconds']._loaded_options = None
  _globals['_SCENARIO'].fields_by_name['timestamps_seconds']._serialized_options = b'\020\001'
  _globals['_OBJECTTYPE']._serialized_start=484
  _globals['_OBJECTTYPE']._serialized_end=585
  _globals['_SCENARIO']._serialized_start=39
  _globals['_SCENARIO']._serialized_end=170
  _globals['_TRACK']._serialized_start=172
  _globals['_TRACK']._serialized_end=293
  _globals['_OBJECTSTATE']._serialized_start=296
  _globals['_OBJECTSTATE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
